version: '2'

services:
  alfresco:
    image: kodermax/docker-alfresco-platform:5.2.f
    environment:
      CATALINA_OPTS: "-Xmx1G -XX:+UseConcMarkSweepGC"
      AWS_ACCESS_KEY_ID: "AKIAIQYOERXOVAST5IRQ"
      AWS_SECRET_ACCESS_KEY: "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"
      ALF_DB_LOGIN: "postgres"
      ALF_DB_NAME: "alfresco"
      ALF_DB_PASSWORD: "alfresco"
      ALF_DB_URL: "jdbc:postgresql://35.188.68.12:5432/alfresco"
    networks:
      - internal
    ports:
      - "8080:8080"
    volumes:
      - "alf_logs:/usr/local/tomcat/logs/"
      - "alf_data:/opt/alf_data"
    tmpfs:
      - /tmp
      - /usr/local/tomcat/temp/
      - /usr/local/tomcat/work/

  share:
    image: kodermax/docker-alfresco-share:5.2.e
    environment:
      CATALINA_OPTS: "-Xmx1G -XX:+UseConcMarkSweepGC"
    depends_on:
      - alfresco
    networks:
      - internal
    ports:
      - "80:8080"
    volumes:
      - "share_logs:/usr/local/tomcat/logs/"
    tmpfs:
      - /tmp
      - /usr/local/tomcat/temp/
      - /usr/local/tomcat/work/

  solr:
    image: kodermax/docker-alfresco-solr:5.2.f
    environment:
      CATALINA_OPTS: "-Xmx1G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:G1HeapRegionSize=8m -XX:MaxGCPauseMillis=200"
    depends_on:
      - alfresco
    networks:
      - internal
    volumes:
      - "solr_logs:/usr/local/tomcat/logs/"
      - "solr_data:/opt/solr_data"
    tmpfs:
      - /tmp
      - /usr/local/tomcat/temp/
      - /usr/local/tomcat/work/

  libreoffice:
    image: kodermax/docker-alfresco-libreoffice:5.2.7
    restart: always
    networks:
      - internal

volumes:
  alf_logs:
  alf_data:
  share_logs:
  solr_logs:
  solr_data:

networks:
  internal: